void move(int vel0, int vel1, int vel2, int vel3);
void forward(int dist, int speed);
void backward(int dist, int speed);
void left(int dist, int speed);
void right(int dist, int speed);
void turn_right(int dist, int speed);
void turn_left(int dist, int speed);
void diag_r_forw(int dist, int speed);
void diag_l_forw(int dist, int speed);
void diag_l_back(int dist, int speed);
void diag_r_back(int dist, int speed);
void right_90();
void left_90();
void wait();
void ssp(int servo, int position);
void forwsquare ();
void backsquare ();
void follow (int distance);
void upslow (int arm, int initial, int final, int speed);
void downslow (int arm, int initial, int final, int speed);
void clear_motors();
void digital_square();
void turn_180();
